### ISSUE TITLE
Error: Invalid packet received! 

### ISSUE THREAD

**Issue by kuchenstrudel** [jrudess/streamdvr#4] opened 2018-01-09 13:11 UTC
I got a crash while I was away with the following error message:
>Error: Invalid packet received! - 578188066 Length == 2908
    at Client._readPacket (/home/foo/streamdvr/node_modules/MFCAuto/lib/Client.js:265:23)
    at Client._readPacket (/home/foo/streamdvr/node_modules/MFCAuto/lib/Client.js:279:22)
    at Client._readData (/home/foo/streamdvr/node_modules/MFCAuto/lib/Client.js:49:14)
    at Socket.client.on (/home/foo/streamdvr/node_modules/MFCAuto/lib/Client.js:634:34)
    at Socket.emit (events.js:159:13)
    at addChunk (_stream_readable.js:265:12)
    at readableAddChunk (_stream_readable.js:252:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onread (net.js:608:20)

The only site that is enabled and used is mfc.

**Comment by jrudess** [comment] 2018-01-10 18:33
I believe I understand the issue and committed a fix to the master branch (but it is not yet in a release version).

**Comment by kuchenstrudel** [comment] 2018-01-11 19:46
Using the current master branch:

> Error: Invalid packet received! - 1869901683 Length == 1971
    at Client._readPacket (/home/foo/streamdvr/node_modules/MFCAuto/lib/Client.js:265:23)
    at Client._readPacket (/home/foo/streamdvr/node_modules/MFCAuto/lib/Client.js:279:22)
    at Client._readData (/home/foo/streamdvr/node_modules/MFCAuto/lib/Client.js:49:14)
    at Socket.client.on (/home/foo/streamdvr/node_modules/MFCAuto/lib/Client.js:634:34)
    at Socket.emit (events.js:159:13)
    at addChunk (_stream_readable.js:265:12)
    at readableAddChunk (_stream_readable.js:252:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onread (net.js:608:20)

**Comment by jrudess** [comment] 2018-01-11 23:22
In mfc.yml can you try setting:

    mfcWebSocket: false

**Comment by kuchenstrudel** [comment] 2018-01-18 17:50
No crash/error since I changed it.

**Comment by jrudess** [comment] 2018-03-03 17:02
With the MFCAuto 5.1.0 upgrade, I would recommend trying to re-enable websockets and see if this occurs anymore.

**Comment by jrudess** [comment] 2018-03-08 06:05
Not resolved.  Just had it happen for the first time as well.

**Comment by kuchenstrudel** [comment] 2018-03-08 17:17
I have it enabled (again) and no error (yet).

**Comment by jrudess** [comment] 2018-03-19 05:34
I need to figure out the appropriate way to catch this error.  Once I can catch it, then that will prevent the script from exiting, and I can destroy and recreate the MFCAuto object to try and get back online.   

This problem only appears reproducible in cases where incoming packets are being corrupted.

**Comment by jrudess** [comment] 2018-03-19 05:44
@ZombieAlex Can you take a look at the stack trace in this issue?  In some bad network situations this particular error can get thrown, and I'd like to resolve this gracefully by either recreating the MFCAuto.Client or disconnecting and reconnecting.

**Comment by ZombieAlex** [comment] 2018-03-19 16:04
That stack could only happen if websockets were turned off and it was using the older pure socket code. You should be fine if you re-enable websockets.

Obviously, I'm throwing there. I could change it to disconnect, and enter the reconnect loop, instead. Feel free to open a bug on me for that.

My only concern would be that it might hide some fundamental change in their server protocol. So I'd like to understand a bit more. Are you seeing this often? Did it only start happening recently? That particular code has existed unchanged for over 3 years and I don't think I've ever personally seen it hit.

**Comment by jrudess** [comment] 2018-03-20 01:04
Thanks for that key piece of info about web-sockets.   I had a case-typo in my code, and so I was actually providing an undefined object for useWebSockets and not actually enabling it like I thought I was.

I only saw this case happen twice during a period where I was having heavy packet loss and retraining the cable modem resolved it, and now I can't reproduce it.

Sounds like this issue should go away completely once I fix my typo and am properly running with websockets.

**Comment by jrudess** [comment] 2018-03-26 02:57
Closing this with release v0.8.0 -- please submit a new sighting if you run into this in the future.

**Closed by jrudess** 2018-03-26 02:57 UTC

**Comment by ZombieAlex** [comment] 2018-04-01 18:32
For what it's worth, I just published MFCAuto v5.2.1 which should prevent this whether you're using websockets or not. Invalid packets will cause a disconnect and reconnect now rather than an uncaught exception.
