### ISSUE TITLE
removing model does not stop ffmpeg process on version 0.7.6.

### ISSUE THREAD

**Issue by Asynchr0nous** [jrudess/streamdvr#22] opened 2018-03-29 14:03 UTC
The problem is solved with all versions above it but they all have one major issue, they get stuck randomly with no errors so it looks like the script is working fine but when you look at the timestamp it will stay the same and adding or removing models will not do anything. if models come online, it will not record.

The issue occurs with the chaturbate so I cannot say if similar issue exists for others as i have them all disabled. I have installed all versions above 0.7.6 and they all have this getting stuck issue.

**Comment by jrudess** [comment] 2018-03-31 03:16
Thanks for narrowing down the problem to a release tag!  I've identified a bug in the 0.7.7 changes.  It doesn't really seem related to the symptoms you've reported, but the patch may be worth trying to see if it improves.  Fix has been checked in to master branch 1f5b045f1398b3b4f39f518e441c2a5313221d62

**Comment by Asynchr0nous** [comment] 2018-03-31 17:49
Just tested this out. the script started recording at 18:05pm and at 18:29pm the model stopped streaming at which point the video was moved to "complete" directory. however, it has been stuck at that position since and as if right now its 18:49pm

**Comment by jrudess** [comment] 2018-03-31 19:26
When this happens, does anything show up at all in the debug log, or nothing prints again?

**Comment by Asynchr0nous** [comment] 2018-03-31 19:48
nothing prints after that point. so that thing that shows up in the log is recording moved

**Comment by Asynchr0nous** [comment] 2018-05-07 23:12
I am currently using node version v9.11.1 on macOS 10.13.1. the issue was still there on older versions of node and i cannot comment on whether the issue exist on node 10 as i only ran the script for few mins before realising that it completely breaks another script i use for mfc.

I also want to mention that the only site i have enabled is chaturbate so maybe try to disabling all others to see if you can repeat the problem.

**Comment by jrudess** [comment] 2018-05-27 21:07
Unfortunately, I have not been able to reproduce this.

**Comment by Asynchr0nous** [comment] 2018-05-27 23:39
it might be something to do with my OS then since thats the only other thing that i can think off.

**Comment by Asynchr0nous** [comment] 2018-06-06 19:42
I've been keeping my eye on this and it seems like the issue might be to do with internet connection. for most part my internet is fine and decently fast but somehow it feels like when searching for models, the script never exists some kind of loop. i had similar issue with my own modified rtmp script for cb and streamte where there was no timeout limit set when making requests which meant every now and then it would do nothing. since i added this timeout limit i've never come across that issue so maybe something similar is happening here?

**Comment by jrudess** [comment] 2018-06-15 20:13
Had it happen to me once finally in the last week as well (both CB and MFC hung, and they have totally different connection code).  On manual restart of the script, recordings started mmediately on both sites.

I had originally added timeouts into all the CB socket connections for exactly this case, because I found some hangs when doing random pulls of the network cable, but will review to see if any are missing.

**Comment by jrudess** [comment] 2018-07-02 02:47
The CB code is completely redone now to rely on streamlink for querying online status.  Please let me know if you still experience the soft lockups.

**Comment by jrudess** [comment] 2018-07-09 23:44
I found a bunch of fun race conditions in threading logic, although most of it was mfc specific.  My belief is that v0.10.0 will resolve these issues, but I can reopen this issue if you still see these problems.

**Closed by jrudess** 2018-07-09 23:44 UTC
